### ISSUE TITLE
Add missing names to list of supporters

### ISSUE THREAD

**Issue by ehsteve** [heliophysicsPy/standards#2]
The following comments are to add names.

**Comment by ehsteve** [comment]
Monica Bobra (Stanford)

**Comment by bla1089** [comment]
It seems my hand writing was illegible. Please change _ A. Atterman_ to _B. L. Alterman_.

**Comment by bsd-conqueror** [comment]
Please add me, too: Minh-Duc Nguyen from Lomonosov Moscow State University.

**Comment by jmason86** [comment]
And me: James Paul Mason (NASA GSFC)

**Comment by dstansby** [comment]
David Stansby (Imperial College London)

**Comment by jtniehof** [comment]
Jonathan Niehof (University of New Hampshire).

Also I think Jon Vandegriff's name got misspelled on the document as-is.

**Comment by johncoxon** [comment]
John Coxon (University of Southampton)

**Comment by rmcgranaghan** [comment]
Please add me, too: Ryan McGranaghan (NASA Jet Propulsion Laboratory). Please note that my affiliation will soon change, however.

**Comment by ehsteve** [comment]
Sabrina Savage (NASA GSFC) by email to me.

**Comment by ehsteve** [comment]
Dr. Alexa J. Halford
The Aerospace Corporation
Space Sciences Department-Chantilly

by email.

**Comment by drsophiemurray** [comment]
Sophie Murray (Trinity College Dublin)

**Comment by rweigel** [comment]
R.S. Weigel (George Mason University)

**Comment by JonathonMSmith** [comment]
Jonathon Smith (NASA GSFC, Catholic University of America)

**Comment by ehsteve** [comment]
Jörg-Micha Jahn, Southwest Research Institute) by email to the list.

**Comment by DanRyanIrish** [comment]
Add me: Daniel Ryan (NASA/GSFC)

**Comment by jklenzing** [comment]
Jeff Klenzing (NASA/GSFC)

**Comment by asherp** [comment]
Asher Pembroke (NASA GSFC)

**Comment by ehsteve** [comment]
Added all of the above names.

**Comment by bla1089** [comment]
A. Alterman is still not my name. It's B. L. Alterman (University of
Michigan). (
https://github.com/heliophysicsPy/standards/issues/2#issuecomment-446451875)

---------------------
B. L. Alterman
Candidate, Applied Physics
Solar and Heliospheric Research Group
Climate and Space Sciences and Engineering
University of Michigan
balterma@umich.edu

**Comment by ehsteve** [comment]
@bla1089 Sorry! Should be fixed now.

**Comment by bla1089** [comment]
Thanks @ehsteve!

Any thoughts on whether we should add ORCIDs to this document - or
somewhere in authorship sections?

---------------------
B. L. Alterman
Candidate, Applied Physics
Solar and Heliospheric Research Group
Climate and Space Sciences and Engineering
University of Michigan
balterma@umich.edu

**Comment by ehsteve** [comment]
@bla1089 that's a good idea. I'll add that as an issue to be resolved by the next release.

**Comment by ehsteve** [comment]
Done for this release. More names can be added to the next release.
